#!/usr/bin/env python

from instrumentationparser import ParseInstrumentation
from instrumentationtotestresulttransformer import Transform
from testresultxmlexporter import ExportXML

inFileName = 'testresults.txt'
outFileName = 'testresults.xml'

inFile = open(inFileName, 'r')
src = inFile.read()
inFile.close()

instrumentation = ParseInstrumentation(src)

testResults = Transform(instrumentation)

xml = ExportXML(testResults)

outFile = open(outFileName, 'w')
outFile.write(xml)
outFile.close()
