#!/usr/bin/env python

from instrumentationparser import ParseInstrumentation
from instrumentationtotestresulttransformer import Transform
from testresultxmlexporter import ExportXML

from optparse import OptionParser

if __name__ == '__main__':
	usage = "usage: %prog [options] <infilename> <outfilename>"
	parser = OptionParser(usage)
	
	(options, args) = parser.parse_args()
	
	if len(args) != 2:
		parser.error("Input and output file names must be specified")

	inFileName = args[0]
	outFileName = args[1]

	inFile = open(inFileName, 'r')
	
	src = ''
	for line in inFile:
		if 'DDM dispatch' in line:
			continue
		if "Can't dispatch DDM chunk" in line:
			continue
		src += line
	
	inFile.close()

	instrumentation = ParseInstrumentation(src)

	testResults = Transform(instrumentation)

	xml = ExportXML(testResults)

	outFile = open(outFileName, 'w')
	outFile.write(xml)
	outFile.close()
